# Starts a dialogue with a defined role,
# which can be simply to "chat" or something more focused like "ask for something".

# The role of the dialogue.
chatbot_msgs/DialogueRole role

# (Optional) The desired locale, using following format:
# the [ISO 639-1 language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), lower-case
# followed by an underscore,
# followed by the [ISO 3166-1 alpha-2 region code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2), upper-case.
# For example, 'en_GB' specifies British English.
# If not provided, the system should use the default locale.
string locale

---
# The JSON dictionary of results obtained from the dialogue, based on the role.
# For example, if the role.name is ASK_ROLE, and the role.configuration is
# {
#   ...
#   "result_schema_properties": {  # -> 
#     "age": {
#       "type": "integer",
#       "minimum": 0,
#   },
# }
# the dictionary could be the following:
#   {"age": "12"}
string results "{}"

# The error message.
# This is not empty only if the dialogue has been aborted.
string error_msg

---
