# Train RASA bots, giving a "chatbot_dir" e.g. /home/.pal/rasa_chatbot_chitchat, and train_all - if set 
# to True it will train all bots, if False, it will train only the default language
 
string chatbot_dir
bool train_all

---
bool bots_trained
---

