# Give language and text input for the chatbot. Example usage in axclient:
# language: 'en_GB'
# text: 'hello, ARI'
# dialogue_id: ''
# Note the first dialogue id should always be '', and would be empty as long as the conversation
# is not ended, else it should use the returned end_conversation value

string language

---
bool server_up
---

