# A request to configure and start a context manager instance.

# The unique ID to be assigned to the context manager instance.
unique_identifier_msgs/UUID id

# It contains three parts:
# 1. The knowledge that is retrieved from the knowledge base.
# 2. The knowledge that is retrieved from the diagnostics messages.
# 3. The custom context that will be appended to the context.

# All three parts are OPTIONAL.

################################################################################
# 1. Filtering of available knowledge in the knowledge base.
################################################################################

string[] filter_classes_env # Retrieve only triplets that contain instances of these classes.
string[] filter_predicates_env # Retrieve only triplets that contain these predicates.

################################################################################
# 2. Filtering of available knowledge in the diagnostics messages.
################################################################################

bool application_context_enabled # Use or not the application diagnostics messages.
bool task_context_enabled # Use or not the task diagnostics messages.
bool skill_context_enabled # Use or not the skill diagnostics messages.

################################################################################
# 3. Provide custom context appended to the retrieved context.
################################################################################

string custom_context # The custom context that will be appended to the context.

---

# The error message.
# This is not empty only if the request could not be fully processed.
string error_msg
